### ISSUE TITLE
`couchmun.com` URL not working on Eduroam

### ISSUE THREAD

**Issue by Zanger67** [gtmun/couchmun#15]
Due to classification by [Palo Alto Networks](https://www.paloaltonetworks.com) -- hosts / maintainers of Eduroam & the Global Protect VPN.
See classification here: https://urlfiltering.paloaltonetworks.com/

## History:
10/23 4pm: Discovered Palo Alto had designated couchmun.com as a phishing website, preventing use on Eduroam
10/23 4:30pm: Request sent to revise categorization as `shareware-and-freeware`
10/23 5pm: Reclassified as `grayware`. This unblocked us on Eduroam but we would rather not be called grayware
--- : Request sent again to recategorize to `shareware-and-freeware`
10/27 10:52pm: New request to revise to `shareware-and-freeware` approved.

**Comment by Zanger67** [comment]
Current state: working but wrong classification so petition to be made

**Comment by Zanger67** [comment]
2nd submission currently IP to change from `greyware` to `freeware/shareware`

**Comment by Zanger67** [comment]
![image](https://github.com/user-attachments/assets/37a41f77-0dee-47ee-83c1-9e90ba6da1d4)
:D

**Comment by endorpersand** [comment]
10/30 Classification changed to "malware"

**Comment by Zanger67** [comment]
Update: In progress -- plans to call for change and clarification as to why it was changed to malware after we've sent in documentation and successfully requested a change to shareware/freeware/open source prior.

**Comment by Zanger67** [comment]
Change request submitted again with reference and asking the reason for our reclassification but will call if no response.

**Comment by Zanger67** [comment]
![image](https://github.com/user-attachments/assets/6851a590-6970-4e9c-b261-8b398e71afe2)
Updated! No info on reason that the previous classification happened for.
